Repository 3DStreamingToolkit/3DStreamingToolkit, pull requests merged in 2018-06, with the labels that each got.

#211 Fix low fps in headless mode (Multithreaded app)
  Libraries/DXUT/Core/DXUT.cpp
Labels: review

#244 Unit tests for the BufferCapturer class
  Libraries/ConfigParser/ConfigParser.Tests/ConfigParserTests.cpp
  Plugins/NativeServerPlugin/inc/buffer_capturer.h
  Plugins/NativeServerPlugin/inc/directx_buffer_capturer.h
  Plugins/NativeServerPlugin/inc/macros.h
  Plugins/NativeServerPlugin/src/buffer_capturer.cpp
  Samples/Server/Directx-SpinningCube/Common/DeviceResources.cpp
  Samples/Server/NativeServersUnitTests/NativeServersTests.cpp
  Samples/Server/NativeServersUnitTests/NativeServersUnitTests.vcxproj
  Samples/Server/NativeServersUnitTests/NativeServersUnitTests.vcxproj.filters
  Samples/Server/NativeServersUnitTests/frame_utils.cpp
  Samples/Server/NativeServersUnitTests/pch.cpp
  Samples/Server/NativeServersUnitTests/pch.h
  Samples/Server/NativeServersUnitTests/stdafx.cpp
  Samples/Server/NativeServersUnitTests/stdafx.h
Labels: in progress

#226 add vcpkg, migrate existing tests to gtest
  .gitignore
  3DStreamingToolKit.gta.runsettings
  3DStreamingToolKit.sln
  CONTRIBUTING.md
  Libraries/ConfigParser/ConfigParser.Tests/ConfigParser.Tests.vcxproj
  Libraries/ConfigParser/ConfigParser.Tests/ConfigParser.Tests.vcxproj.filters
  Libraries/ConfigParser/ConfigParser.Tests/ConfigParserTests.cpp
  Libraries/ConfigParser/ConfigParser.Tests/packages.config
  Libraries/ConfigParser/ConfigParser.Tests/stdafx.cpp
  Libraries/ConfigParser/ConfigParser.Tests/stdafx.h
  Plugins/NativeServerPlugin/inc/directx_buffer_capturer.h
  Plugins/NativeServerPlugin/inc/macros.h
  Samples/Server/NativeServer.Tests/NativeServer.Tests.vcxproj
  Samples/Server/NativeServer.Tests/NativeServer.Tests.vcxproj.filters
  Samples/Server/NativeServer.Tests/NativeServersTests.cpp
  Samples/Server/NativeServer.Tests/frame_utils.cpp
  Samples/Server/NativeServer.Tests/packages.config
  Samples/Server/NativeServer.Tests/pch.cpp
  Samples/Server/NativeServer.Tests/pch.h
  Samples/Server/NativeServer.Tests/targetver.h
  Samples/Server/NativeServer.Tests/webrtc.h
  Samples/Server/NativeServer.Tests/webrtcH264.h
  Samples/Server/NativeServersUnitTests/NativeServersTests.cpp
  Samples/Server/NativeServersUnitTests/tests.runsettings
  Utilities/test.ps1
  conf/BaseProject.props
  conf/GTest.props
  conf/gtest_main.cpp
  test.cmd
Labels: enhancement

#253 Minor correction to gtest docs
  Samples/Server/NativeServer.Tests/NativeServersTests.cpp
Labels: in progress

#257 Hotfix/issue209: Unit testing for RTP Package and decoding
  Samples/Server/NativeServer.Tests/NativeServer.Tests.vcxproj
  Samples/Server/NativeServer.Tests/NativeServer.Tests.vcxproj.filters
  Samples/Server/NativeServer.Tests/NativeServersTests.cpp
  Samples/Server/NativeServer.Tests/frame_generator.cc
  Samples/Server/NativeServer.Tests/webrtcH264.h
Labels: in progress

#258 Added nvpipe initialization to the gpu and driver test, to ensure cor…
  Samples/Server/NativeServer.Tests/NativeServersTests.cpp
Labels: in progress

#265 Functional tests for end-to-end single client to server
  Libraries/UserInterface/inc/client_main_window.h
  Libraries/UserInterface/inc/server_main_window.h
  Libraries/UserInterface/src/client_main_window.cpp
  Libraries/UserInterface/src/main_window.cpp
  Libraries/UserInterface/src/server_main_window.cpp
  Plugins/NativeServerPlugin/inc/buffer_capturer.h
  Plugins/NativeServerPlugin/inc/multi_peer_conductor.h
  Plugins/NativeServerPlugin/src/buffer_capturer.cpp
  Plugins/NativeServerPlugin/src/multi_peer_conductor.cpp
  Plugins/NativeServerPlugin/src/peer_conductor.cpp
  Plugins/UnityServerPlugin/StreamingUnityServerPlugin.cpp
  Samples/Client/DirectxWin32/StreamingDirectxClient.vcxproj
  Samples/Client/DirectxWin32/StreamingDirectxClient.vcxproj.filters
  Samples/Client/DirectxWin32/inc/conductor.h
  Samples/Client/DirectxWin32/inc/data_channel_handler.h
  Samples/Client/DirectxWin32/inc/defs.h
  Samples/Client/DirectxWin32/inc/macros.h
  Samples/Client/DirectxWin32/inc/win32_data_channel_handler.h
  Samples/Client/DirectxWin32/pch.h
  Samples/Client/DirectxWin32/src/conductor.cpp
  Samples/Client/DirectxWin32/src/main.cpp
  Samples/Client/DirectxWin32/src/win32_data_channel_handler.cpp
  Samples/Server/Directx-Multithreaded/Multithreaded.cpp
  Samples/Server/Directx-SpinningCube/App.cpp
  Samples/Server/NativeServer.Tests/NativeServer.Tests.vcxproj
  Samples/Server/NativeServer.Tests/NativeServer.Tests.vcxproj.filters
  Samples/Server/NativeServer.Tests/NativeServersTests.cpp
  Samples/Server/NativeServer.Tests/frame_generator.cpp
  Samples/Server/NativeServer.Tests/webrtc.h
  Samples/Server/OpenGL-SpinningCube/App.cpp
Labels: in progress

#263 Send Turn Server info to Client on connection
  Plugins/NativeServerPlugin/inc/peer_conductor.h
  Plugins/NativeServerPlugin/src/peer_conductor.cpp
  Samples/Client/DirectxWin32/src/conductor.cpp
  Samples/Client/WebClient/README.md
  Samples/Client/WebClient/app.js
  Samples/Client/WebClient/index.html
  Samples/Client/WebClient/package-lock.json
  Samples/Client/WebClient/package.json
Labels: in progress

#272 Multi-clients to server end-to-end test
  Libraries/UserInterface/inc/client_main_window.h
  Samples/Client/DirectxWin32/inc/conductor.h
  Samples/Client/DirectxWin32/inc/data_channel_handler.h
  Samples/Server/NativeServer.Tests/NativeServersTests.cpp
Labels: in progress
